"use client"

import { ChevronLeft, CreditCard } from "lucide-react"
import type { FirestoreOrder } from "@/components/order-popup-panel"

export function PaymentsPage({ orders, onBack }: { orders: FirestoreOrder[]; onBack: () => void }) {
  const payments = orders.filter(order => order.status === "accepted" || ["driver_assigned", "at_store", "picked_up", "delivered", "completed", "ready_for_pickup"].includes(order.status)).sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())
  const total = payments.reduce((sum, order) => sum + order.subtotal, 0)
  return <div className="flex h-full flex-col bg-background"><header className="shrink-0 border-b border-border bg-card px-4 pb-4 pt-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button onClick={onBack} aria-label="Go back" className="text-card-foreground"><ChevronLeft className="size-6" /></button><h1 className="text-2xl font-bold text-card-foreground">Payments</h1></div><div className="text-right"><p className="text-xs text-muted-foreground">Total captured</p><p className="font-bold text-primary">ZMW {total.toFixed(2)}</p></div></div></header><main className="flex-1 overflow-y-auto px-4 py-4 scrollbar-hide"><div className="flex flex-col gap-3">{payments.length === 0 ? <div className="py-16 text-center text-muted-foreground">No captured payments yet.</div> : payments.map(order => <article key={order.id} className="rounded-xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start gap-3"><div className="flex size-11 shrink-0 items-center justify-center rounded-xl bg-primary/10"><CreditCard className="size-5 text-primary" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><h2 className="font-bold text-card-foreground">{order.userName}</h2><p className="text-xs text-muted-foreground">Order #{order.orderId}</p></div><p className="shrink-0 font-bold text-primary">ZMW {order.subtotal.toFixed(2)}</p></div><p className="mt-2 text-sm text-muted-foreground">{order.destinationAddress}</p><div className="mt-3 flex flex-col gap-1 border-t border-border/50 pt-2">{order.items.map((item, index) => <div key={index} className="flex justify-between gap-3 text-xs text-muted-foreground"><span>{item.name}{item.quantity && item.quantity > 1 ? ` x${item.quantity}` : ""}</span><span>ZMW {(item.price * (item.quantity || 1)).toFixed(2)}</span></div>)}<div className="mt-1 flex justify-between text-xs font-semibold text-card-foreground"><span>Paid</span><span>ZMW {order.subtotal.toFixed(2)}</span></div></div></div></div></article>)}</div></main></div>
}
